Updating Coap documentation after esp-idf 4 update
pycom/pycom-documentation pull request #292
Opened 2020-07-01 12:34 UTC by geza-pycom

2021-01-21 13:23 UTC, peter-pycom requested changes

2021-01-21 13:23 UTC, peter-pycom commented on content/firmwareapi/pycom/network/espnow.md
> +p1.lmk(b'0123456789123456')
we're using bytes here, but a string for pmk(). could this be unified?

2021-01-21 13:23 UTC, peter-pycom commented on content/firmwareapi/pycom/network/espnow.md
> +    # The Peer p1 will only receive this message if the same LMK is configured for the Peer object created for this device on the other device also
speaking of which - shouldn't we have an example for the other end as well? Is the script here the master and then we should have one more script for encrypted peer 1 and another one for unencrypted peer 2?

Also, lately the docs are more cleanly separated between API here and examples there. I personally don't mind the odd one-line-example in the API, but larger scripts I think make sense on a dedicated example page

2021-01-21 13:23 UTC, peter-pycom commented on content/firmwareapi/pycom/network/coap.md
> +Due to limitations of the underlying ESP-IDF/libcoap library, new resources cannot be added via POST request.
Not sure, I really get it:

Due to a limitation you can't do this thing via method X. 

Well, that might be true, however there is method Y now, so you CAN do this thing via that method Y ... so ... Is this warning still relevant or are we just confusing people?

2021-01-21 13:23 UTC, peter-pycom commented on content/firmwareapi/pycom/network/espnow.md
> +This module implements interface to ESP-NOW protocol.
Please add a link to some background about what this is. 

Maybe jsut https://www.espressif.com/en/products/software/esp-now/overview or maybe you have a better one ...

2021-01-21 13:23 UTC, peter-pycom commented on content/firmwareapi/pycom/network/coap.md
> +* `destination` is the IPv4 Address of the CoAp Server where this CoAp Client Session has joined.
further down you use the style of `Item 0` is this and `Item 1` is that. I guess this is also a list here (and not a named tuple right?) then it might make sense to use the same style here

2021-01-21 13:23 UTC, peter-pycom commented on content/firmwareapi/pycom/network/coap.md
> +* `resource` is the new resource which has been created
is resource param missing from header?

2021-01-21 13:23 UTC, peter-pycom commented on content/firmwareapi/pycom/network/coap.md
> +session1 = Coap.new_client_session("192.168.0.234", 5683)
where does this ip address refer to? can we put dummy value and explanation?

2021-01-21 13:23 UTC, peter-pycom commented on content/firmwareapi/pycom/network/coap.md
> +    new_resource.set_details(mediatype=Coap.MEDIATYPE_TEXT_PLAIN, max_age=132, etag=True)
explain 132?

2021-01-21 13:23 UTC, peter-pycom commented on content/firmwareapi/pycom/network/coap.md
> +id = session.send_request(Coap.REQUEST_GET, payload="amqp://artemis:5672/dish.app1.FjhBV78.telemetry", token=imei, include_options=False)
I'm confused. what's a dish telemetry server? amqp? artemis? FjhBV78? is an IMEI required for a minimal coap example? use a dummy value?

also, the three requests above, I'm not sure, I am really learning the lesson here ... either I need more comments, or maybe this is repetitive and we could make the example smaller?

2021-01-21 13:23 UTC, peter-pycom commented on content/firmwareapi/pycom/network/coap.md
> +session = Coap.new_client_session("192.168.0.234", 5683)
values

2021-01-22 13:54 UTC, geza-pycom commented on content/firmwareapi/pycom/network/espnow.md
> +p1.lmk(b'0123456789123456')
I am not sure I fully understand this. Could you please give more details?

2021-01-22 13:58 UTC, geza-pycom commented on content/firmwareapi/pycom/network/coap.md
> +    new_resource.set_details(mediatype=Coap.MEDIATYPE_TEXT_PLAIN, max_age=132, etag=True)
Just a random value I picked, this is fully application dependent.
In CoAP the value of the Max-Age parameter means: "_The option value is an integer number of seconds between 0 and 2**32-1 inclusive (about 136.1 years)._"

2021-01-22 13:59 UTC, geza-pycom commented on content/firmwareapi/pycom/network/coap.md
> +session = Coap.new_client_session("192.168.0.234", 5683)
What should be "values" ? Sorry, github does not show which word/sentence you are referring.

2021-01-22 14:01 UTC, geza-pycom commented on content/firmwareapi/pycom/network/coap.md
> +id = session.send_request(Coap.REQUEST_GET, payload="amqp://artemis:5672/dish.app1.FjhBV78.telemetry", token=imei, include_options=False)
It is a special server which accept messages similar to a CoAp server, but the URI starts with "amqp" and no Option is included in the message. @Xykon can tell more about this.

2021-01-22 14:02 UTC, geza-pycom commented on content/firmwareapi/pycom/network/coap.md
> +session1 = Coap.new_client_session("192.168.0.234", 5683)
This is the address of the remote device which you would like to "connect" (as CoAp goes via UDP connect() is not correct phrasing).

2021-01-22 14:04 UTC, geza-pycom commented on content/firmwareapi/pycom/network/coap.md
> +* `resource` is the new resource which has been created
It should be removed, leftover from copy-paste.

2021-01-22 14:04 UTC, geza-pycom commented on content/firmwareapi/pycom/network/coap.md
> +* `destination` is the IPv4 Address of the CoAp Server where this CoAp Client Session has joined.
Agreed.

2021-01-22 14:05 UTC, geza-pycom commented on content/firmwareapi/pycom/network/coap.md
> +Due to limitations of the underlying ESP-IDF/libcoap library, new resources cannot be added via POST request.
By default as per my understanding there is a difference between PUT and POST.
In PUT you must specify the URI of the resource you want to create, while in POST you do not specify it, you expect that the server creates it for you and in its response it sends back the URI. The first is supported, second is not.

2021-01-22 14:06 UTC, geza-pycom commented on content/firmwareapi/pycom/network/espnow.md
> +This module implements interface to ESP-NOW protocol.
I can add a link, but we also do not add link to other protocols, like Bluetooth.

2021-01-22 14:07 UTC, geza-pycom commented on content/firmwareapi/pycom/network/espnow.md
> +    # The Peer p1 will only receive this message if the same LMK is configured for the Peer object created for this device on the other device also
The example of the other s basically the same, just calling ESPNOW.add_peer() with different MAC address. I can add example if needed.
Also I can move the examples to a dedicated location if needed.

2021-01-22 14:08 UTC, geza-pycom reviewed
Please check my comments.

2021-01-22 14:15 UTC, geza-pycom commented
@peter-pycom : just heads up that please do not merge this once we have discussed all the comments, I am not sure whether this is the current branch to merge these updates.

2021-01-26 18:21 UTC, geza-pycom commented on content/firmwareapi/pycom/network/coap.md
> +* `resource` is the new resource which has been created
@peter-pycom : please check the updated version where this was modified, we forget to discuss this point during our call.

2021-02-10 17:09 UTC, peter-pycom approved these changes, later dismissed
Nice. It's much clearer to me now. Thanks.

2021-02-10 17:27 UTC, peter-pycom requested changes

2021-02-10 17:27 UTC, peter-pycom commented on content/firmwareapi/pycom/network/coap.md
> +#### Coap.new_client_session(address, *, port=5683, psk=None, identity=None)
new_client_session() has lost the protocol param, but remove_client_session() still has it. intentional?

2021-02-10 17:30 UTC, geza-pycom commented on content/firmwareapi/pycom/network/coap.md
> +#### Coap.new_client_session(address, *, port=5683, psk=None, identity=None)
Yes it is.
When you call new_client_session() the Protocol is figured out based on the PSK and Identity parameters.
When you remove it may happen that you have 2 Clients connected to the same Port, but one is using UDP the other is DTLS.

2021-03-03 11:11 UTC, peter-pycom commented
I think you guys agreed on a branch for this, right? Can you update the PR?

2021-03-03 16:37 UTC, geza-pycom commented
New request opened towards correct branch: https://github.com/pycom/pycom-documentation/pull/387

2021-03-03 16:37 UTC, closed without merging