Added a guide to perform differential OTA udpate
pycom/pycom-documentation pull request #306
Opened 2020-07-31 11:58 UTC by salal-m

2020-07-31 12:10 UTC, gijsio commented
Thanks for the guide! I'm sure it must be an advance topic. 
Will you allow me to make some changes and turn it more into a step-by-step guide? I feel like we are skipping some things for people who do not upload firmware on a daily basis :) 
Let me know!

2020-07-31 12:17 UTC, salal-m commented
Sure. If there are any updates I can do, let me know.
BTW, the changes in the firmware for Differential Update are not published yet. So we should probably merge this PR after that is done.

2020-08-03 07:52 UTC, peter-pycom commented
Indeed. Please DO review & improve, but DO NOT merge yet

2020-08-03 10:59 UTC, gijsio commented
Sorry, commited some things on the wrong branch :') I rewrote the differential OTA a bit so it looks like a guide. Im also not too happy yet with the other OTA firmware update we describe, as it looks really confusing, if you could take a look there as well? Thanks

2020-08-03 11:41 UTC, salal-m commented
Hi @gijsio 
The steps in the Differential OTA are an extension of the OTA Firmware update procedure, so it's not an either/or scenario. I will make the changes to fix this. Maybe some lines and a reference can be added to the OTA  Firmware Update page, so I'll look at it as well.

2020-08-03 17:31 UTC, peter-pycom commented
> Sorry, commited some things on the wrong branch :') I rewrote the differential OTA a bit so it looks like a guide. Im also not too happy yet with the other OTA firmware update we describe, as it looks really confusing, if you could take a look there as well? Thanks

Please revert the unrelated changes!

2020-08-03 18:27 UTC, peter-pycom requested changes

2020-08-03 18:27 UTC, peter-pycom commented on content/updatefirmware/_index.md
> +* [Device (Differential OTA)](/updatefirmware/diff_ota/)
it shows up above OTA, please make sure it is below

2020-08-03 18:27 UTC, peter-pycom commented on content/updatefirmware/diff_ota.md
> +> Note: You can only perform the differential updates if your current firmware version supports this feature. The target can be any version (above 1.20).
Please add a sentence/reformulate the paragraph, so we start with what you can do/what this is for, before we have the disclaimer about what you can't do with this

Also please clarify how I know/make sure whether my firmware "supports this feature"? --- Mhhh. Might be difficult, other than filling in the version number when we release it. Please keep in mind to add/update this after we release it!

2020-08-03 18:27 UTC, peter-pycom commented on content/updatefirmware/diff_ota.md
> +* [bsdiff](/gitbook/assets/DiffCreator.tar.gz)
the link and in the text below you call it bsdiff, but the thing that I download is called DiffCreator. Please make it consistent

2020-08-03 18:27 UTC, peter-pycom commented on content/updatefirmware/diff_ota.md
> +> It is also possible to do an OTA differential firmware update using [**OTA Method A**](../ota).
Why "also"? So far I haven't done an update in any way ...

2020-08-03 18:27 UTC, peter-pycom commented on content/updatefirmware/diff_ota.md
> +* [bsdiff](/gitbook/assets/DiffCreator.tar.gz)
Is this our creation? Should it have a version number? Are we releasing the source code for it? Under what license? If so, probably good to at least add a README with the link to the source

2020-08-03 18:27 UTC, peter-pycom commented on content/updatefirmware/diff_ota.md
> +    ./diff_creator source.bin target.bin patch.bin
I have an exe called create_diff, I don't have a diff_creator.

2020-08-03 18:27 UTC, peter-pycom commented on content/updatefirmware/diff_ota.md
> +    * `target.bin' is the target binary
formatting! I think it's a apostrophy instead of a backtick

2020-08-03 18:27 UTC, peter-pycom commented on content/updatefirmware/diff_ota.md
> +    > Note: replace the `.bin` filenames with the actual filenames.
I think that's clear. I suggest to drop the note otherwise the text is soo "colorful" with green boxes

2020-08-03 18:27 UTC, peter-pycom commented on content/updatefirmware/diff_ota.md
> +3. Now, download the `patch.bin` file to the device using [...] . Note that this file is considerably smaller than the `target.bin` file.
[...] is there some part missing? Yes, this does need more explanation!

2020-08-03 18:27 UTC, peter-pycom commented on content/updatefirmware/diff_ota.md
> +3. Now, download the `patch.bin` file to the device using [...] . Note that this file is considerably smaller than the `target.bin` file.
Is it a given that it is considerably smaller, or should we be more generic? ... it can be ... check whether ...

2020-08-03 18:27 UTC, peter-pycom commented on content/updatefirmware/diff_ota.md
> +    Differential Update Image detected. The device will restart to apply the patch.
I've never seen this line ...

2020-08-03 18:27 UTC, peter-pycom commented on content/updatefirmware/diff_ota.md
> +    Patching SUCCESSFUL.
I've never seen these lines. I'm following "Method A"

2020-08-04 09:17 UTC, gijsio commented on content/updatefirmware/_index.md
> +* [Device (Differential OTA)](/updatefirmware/diff_ota/)
I think we should put differential OTA as a subsection of device OTA reading this back now

2020-08-04 09:18 UTC, gijsio commented on content/updatefirmware/diff_ota.md
> +> Note: You can only perform the differential updates if your current firmware version supports this feature. The target can be any version (above 1.20).
Yes! Good point. I put this at the top as we do not want people to read the guide and then figure out it does not work for them.

2020-08-04 09:19 UTC, gijsio commented on content/updatefirmware/diff_ota.md
> +* [bsdiff](/gitbook/assets/DiffCreator.tar.gz)
Im not sure.. If this is our thing, we should maybe put it on software.pycom.io? or in the Github libraries repo

2020-08-04 09:20 UTC, gijsio commented on content/updatefirmware/diff_ota.md
> +> It is also possible to do an OTA differential firmware update using [**OTA Method A**](../ota).
Im not sure about the whole OTA (without differential) process, maybe we should review that as well

2020-08-04 09:21 UTC, gijsio commented on content/updatefirmware/diff_ota.md
> +3. Now, download the `patch.bin` file to the device using [...] . Note that this file is considerably smaller than the `target.bin` file.
Then we'd need some numbers on this

2020-08-11 09:08 UTC, peter-pycom requested changes

2020-08-11 09:08 UTC, peter-pycom commented on content/advance/coredump.md
> +title: "Troubleshooting Coredumps"
pls revert this and other unrelated changes

2020-08-11 09:08 UTC, peter-pycom commented on content/updatefirmware/diff_ota.md
> +Differential update allows you to update your device using a differntial update file(patch file) instead of a complete new binary. This can save a considerable amount of space and bandwidth while dow
differntial -> differential

2020-08-11 09:08 UTC, peter-pycom commented on content/updatefirmware/diff_ota.md
> +Differential update allows you to update your device using a differntial update file(patch file) instead of a complete new binary. This can save a considerable amount of space and bandwidth while dow
file(patch -> space missing

2020-08-11 09:08 UTC, peter-pycom commented on content/updatefirmware/diff_ota.md
> +> Note: The finary files used for this are the *.bin* files generated after firmware is built. If you have downloaded the firmware as a compressed archive, you can decompress it to find the *.bin* fi
finary -> binary
after firmware -> after the firmware

2020-08-11 09:19 UTC, salal-m commented on content/updatefirmware/_index.md
> +* [Device (Differential OTA)](/updatefirmware/diff_ota/)
I fixed the sequence. I think keeping it at OTA level improves the visibility of the feature.
Or should I make it a sub-section?

2020-08-11 09:20 UTC, peter-pycom commented on content/updatefirmware/_index.md
> +* [Device (Differential OTA)](/updatefirmware/diff_ota/)
I think same level is fine

2020-08-11 12:48 UTC, peter-pycom approved these changes
lgtm!

2020-08-11 12:58 UTC, merged