reworked machine index api
pycom/pycom-documentation pull request #309
Opened 2020-08-12 14:51 UTC by gijsio

Do not merge yet.. 
Reworking API information

2020-08-27 13:38 UTC, gijsio commented
This is not quite ready, but contains a lot of fixes for various pages, I think we should review it now or it will take too long

2020-08-27 16:26 UTC, peter-pycom requested changes

2020-08-27 16:26 UTC, peter-pycom commented on config.toml
> +    name = "Pymesh BLE"
link doesn't work

2020-08-27 16:26 UTC, peter-pycom commented on content/firmwareapi/micropython/array.md
> +Adapting the typecode to the array-type you want to create can save a lot of space on the microcontroller
new line missing

2020-08-27 16:26 UTC, peter-pycom commented on content/firmwareapi/micropython/builtin.md
> +### any([])
what do the rectangular brackets stand for? Ah. I guess you mean iterable .... like a list. This is very confusing though. in other places it denotes optional arguments like machine.sleep()

2020-08-27 16:26 UTC, peter-pycom commented on content/firmwareapi/micropython/builtin.md
> +> You can also use `a-bj`
a what?! don't understand `a-bj`

2020-08-27 16:26 UTC, peter-pycom commented on content/firmwareapi/pycom/aes.md
> +    * `AES.MODE_ECB`: Electronic Code Book. Simplest encryption mode. It does not hide data patterns well (see this article for more info)
link missing. but actually, maybe we don't really venture into the pros and cons of cyphers inside the API docs?!

2020-08-27 16:26 UTC, peter-pycom commented on content/firmwareapi/pycom/aes.md
> +    * `AES.MODE_CFB`: Cipher feedback. `plaintext` and `ciphertext` are processed in segments of `segment_size` bits. Works a stream cipher.
works AS a ?!

2020-08-27 16:26 UTC, peter-pycom commented on content/firmwareapi/micropython/builtin.md
formatting changes from here on ... ok we just spoke you are aware of this. fine if you want to merge this before fixing it, but then please treat this with HIGH priority to fix the layout again!

2020-08-27 16:26 UTC, peter-pycom commented on content/firmwareapi/pycom/machine/_index.md
either add "or another wakeup source is configured", or better yet get rid of the "If a value in milliseconds..." sentence, because you will explain it right after anyway

2020-08-27 16:26 UTC, peter-pycom commented on content/firmwareapi/pycom/machine/adc.md
> +print('hello world')
you forgot the dev hack in here

2020-08-27 16:26 UTC, peter-pycom commented on content/firmwareapi/pycom/machine/adc.md
> -## class ADCChannel
we lost the section header for the class ADCChannel

2020-08-27 16:26 UTC, peter-pycom commented on content/firmwareapi/pycom/machine/pin.md
> +* `Pin.IN` or 1
please don't put literal values like 1, 2, 7. that's what we have named constants for.

2020-08-27 16:26 UTC, peter-pycom commented on content/firmwareapi/pycom/machine/touch.md
> +The Touch module allows for certain GPIO pins (`P2`,`P3`,`P4`,`P6`,`P8`,`P9`,`P10`,`P19`,`P20`) to accept touch inputs.
I don't get it. What is a touch input?

2020-08-27 16:26 UTC, peter-pycom commented on content/firmwareapi/pycom/network/bluetooth/_index.md
> +* `id` Only one Bluetooth peripheral available so must always be 0	* `id` Only one Bluetooth peripheral available so must always be 0.
the init section is duplicated!

2020-08-27 16:26 UTC, peter-pycom commented on content/firmwareapi/pycom/network/bluetooth/btmesh.md
> +---
All new? I assume someone else wrote/reviewed this?! I only eyeballed it

2020-08-27 16:26 UTC, peter-pycom commented on content/firmwareapi/pycom/network/lora/_index.md
>  This class provides a LoRaWAN 1.0.2 compliant driver for the LoRa network processor in the LoPy and FiPy. Below is an example demonstrating LoRaWAN Activation by Personalisation usage:
remove: "Below is an example ..."

2020-08-27 16:26 UTC, peter-pycom commented on content/firmwareapi/pycom/network/lora.md
> -* `bandwidth` is the channel bandwidth in KHz. In the 868 band the accepted values are `LoRa.BW_125KHZ` and `LoRa.BW_250KHZ`. In the 915 band the accepted values are `LoRa.BW_125KHZ` and `LoRa.BW_500
isn't that still relevant: "In the 868 band the accepted ..."?

2020-08-27 16:26 UTC, peter-pycom commented on content/firmwareapi/pycom/network/lora.md
> -* `dr`: is an optional value to specify the initial data rate for the Join Request. Possible values are 0 to 5 for **EU868**, or 0 to 4 for **US915**.
isn't that still relevant: Possible values are 0 to 5 for **EU868**, or 0 to 4 for **US915**.

2020-08-27 16:26 UTC, peter-pycom commented on content/firmwareapi/pycom/network/lora.md
> -#### lora.bandwidth(\[bandwidth\])
did we lose lora.bandwidth() ?

2020-08-27 16:26 UTC, peter-pycom commented on content/firmwareapi/pycom/network/lora.md
> -Get or set the frequency in raw LoRa mode (`LoRa.LORA`). The allowed range is between `863000000` and `870000000` Hz for the 868 MHz band version or between `902000000` and `928000000` Hz for the 915
did we lose the ranges?

2020-08-27 16:26 UTC, peter-pycom commented on content/firmwareapi/pycom/network/lora/_index.md
> +For various other complete LoRa examples, check [here](/tutorials/networks/lora/) for examples.
For complete LoRa examples, check here.

2020-08-27 16:26 UTC, peter-pycom commented on content/firmwareapi/pycom/network/lora.md
> -# selecting non-confirmed type of messages
not sure how relevant, but I just wanted to mention, this example of confirmed / non-confirmed is gone after this PR ...

2020-08-27 16:26 UTC, peter-pycom commented on content/firmwareapi/pycom/network/lte.md
> -When carrier is specified in `LTE()` or `LTE.init()` (eg. `lte = LTE(carrier=verizon)`) No need to specify band, apn or type these parameters are already programmed in to the LTE modem for each carri
did we lose this info?

2020-08-27 16:26 UTC, peter-pycom commented on content/firmwareapi/pycom/pycom.md
> +Return a list of pulses at `pin`. The methods scans for transitions at `pin` and returns a list of tuples, each telling the pin value and the duration in microseconds of that value. `pin` is a pin ob
not transitions -> no transitions

2020-08-28 07:26 UTC, gijsio commented on content/firmwareapi/micropython/builtin.md
> +> You can also use `a-bj`
`a-bj` is a common notation for complex numbers, I added an example

2020-08-28 07:27 UTC, gijsio commented on content/firmwareapi/pycom/aes.md
> +    * `AES.MODE_ECB`: Electronic Code Book. Simplest encryption mode. It does not hide data patterns well (see this article for more info)
done

2020-08-28 07:56 UTC, gijsio commented on content/firmwareapi/micropython/builtin.md
> +### any([])
I tried to improve the notation

2020-08-28 07:57 UTC, gijsio commented on content/firmwareapi/pycom/network/lora.md
> -# selecting non-confirmed type of messages
This example should be in the 'tutorials and examples' tab as well

2020-08-28 08:05 UTC, gijsio commented on content/firmwareapi/pycom/network/lora.md
> -Get or set the frequency in raw LoRa mode (`LoRa.LORA`). The allowed range is between `863000000` and `870000000` Hz for the 868 MHz band version or between `902000000` and `928000000` Hz for the 915
We did not lose the ranges, I just did not want to include them for all frequency ranges we currently support. People can probably find themselves the supported frequencies, and we have an error message stating whether the frequency is out of bounds as well

2020-08-28 08:22 UTC, gijsio commented on content/firmwareapi/pycom/network/lora.md
> -#### lora.bandwidth(\[bandwidth\])
Yes, accidentally

2020-08-28 08:41 UTC, gijsio commented on content/firmwareapi/pycom/network/bluetooth/btmesh.md
> +---
It came from the development documentation

2020-08-28 08:42 UTC, gijsio commented on content/firmwareapi/pycom/machine/adc.md
> +print('hello world')
Ill take it out, but leave the identifiers

2020-08-28 08:43 UTC, gijsio commented on content/firmwareapi/pycom/network/lte.md
> -When carrier is specified in `LTE()` or `LTE.init()` (eg. `lte = LTE(carrier=verizon)`) No need to specify band, apn or type these parameters are already programmed in to the LTE modem for each carri
Im not sure this is still correct?

2020-08-28 08:54 UTC, gijsio commented on content/firmwareapi/pycom/network/lora.md
> -* `dr`: is an optional value to specify the initial data rate for the Join Request. Possible values are 0 to 5 for **EU868**, or 0 to 4 for **US915**.
I verified this with the firmware source, it does not check out

2020-08-28 10:00 UTC, peter-pycom approved these changes

2020-08-28 10:01 UTC, merged