fixed minor mistakes in lte modem update
pycom/pycom-documentation pull request #318
Opened 2020-09-01 07:34 UTC by gijsio

2020-09-01 08:59 UTC, peter-pycom requested changes

2020-09-01 08:59 UTC, peter-pycom commented on content/updatefirmware/ltemodem.md
> +The modem firmware files are password protected. In order to download them, head to https://forum.pycom.io and become a member (if you aren't already) and go [here](https://forum.pycom.io/topic/4020/
I like the direct link, but I also like the accessibility of the description of where to go instead of "here". Not least, it is useful when links break (as they do)

2020-09-01 08:59 UTC, peter-pycom commented on content/updatefirmware/ltemodem.md
> +    # WARNING! If you are updating from version 33080, use the updater.elf file as well, this is not needed for the upgdiff file.
are you positively sure about this? I think I heard otherwise from Christian!

2020-09-01 10:19 UTC, gijsio commented on content/updatefirmware/ltemodem.md
> +    # WARNING! If you are updating from version 33080, use the updater.elf file as well, this is not needed for the upgdiff file.
I checked again, for 33080 using upgdiff, you do not need updater.elf

2020-09-01 10:19 UTC, gijsio commented on content/updatefirmware/ltemodem.md
> +The modem firmware files are password protected. In order to download them, head to https://forum.pycom.io and become a member (if you aren't already) and go [here](https://forum.pycom.io/topic/4020/
Ill add it back!

2020-09-11 08:35 UTC, Xykon approved these changes

2020-09-11 09:34 UTC, peter-pycom approved these changes

2020-09-11 10:03 UTC, merged