Api fix
pycom/pycom-documentation pull request #339
Opened 2020-10-19 13:27 UTC by gijsio

2020-10-21 08:35 UTC, peter-pycom requested changes

2020-10-21 08:35 UTC, peter-pycom commented on content/datasheets/expansionboards/expansion3.md
> +The expansion board contains 6 jumpers labeled:
7

2020-10-21 08:35 UTC, peter-pycom commented on content/firmwareapi/pycom/network/lora/_index.md
> +* `device_class` sets the LoRaWAN device class. Go [here](https://www.thethingsnetwork.org/docs/lorawan/classes.html) to learn more about the LoRa device classes. Can be either:
I generally prefer to name links in a descriptive way, rather than "here". How about smt like

Visit the [TTN website](...) to learn more ....

2020-10-21 08:35 UTC, peter-pycom commented on content/firmwareapi/pycom/network/lora/_index.md
> +> Note that the tuple will only contain the respective information after receiver and/or sending LoRa packets.
should that be "receiving" ?

2020-10-21 08:35 UTC, peter-pycom commented on content/firmwareapi/pycom/network/lte.md
> -### lte.send_at_cmd(cmd, [delay=10000])
why? https://github.com/pycom/pycom-micropython-sigfox/blob/Dev/esp32/mods/modlte.c#L1240

2020-10-23 09:03 UTC, gijsio commented on content/firmwareapi/pycom/network/lte.md
> -### lte.send_at_cmd(cmd, [delay=10000])
Ah, I wasnt aware we put it back in..

2020-11-24 14:59 UTC, peter-pycom commented on content/datasheets/expansionboards/expansion3.md
> +- TX: TX UART (GPIO1) communication of the development board to the Expansionboard
should we mention the GPIOx numbering scheme here? or should we use the Px scheme?

2020-11-24 15:18 UTC, peter-pycom approved these changes

2020-11-24 15:18 UTC, merged