added additional antenna selection descriptions
pycom/pycom-documentation pull request #344
Opened 2020-11-27 15:49 UTC by gijsio

2020-12-04 12:19 UTC, peter-pycom requested changes

2020-12-04 12:19 UTC, peter-pycom commented on content/firmwareapi/pycom/network/bluetooth/_index.md
> +    With our development boards it defaults to using the internal antenna, but in the case of an OEM module, the antenna pin (`P12`) is not used, so it's free to be used for other things.	With our de
can we fix the duplicated text as well while we're here?

2020-12-04 12:19 UTC, peter-pycom commented on content/firmwareapi/pycom/network/bluetooth/_index.md
why are we removing this? actually, I not sure I fully get it .... It's like a decision tree right?

- INT
- EXT
- MAN
  - do xyz for int, abc, for ext, how exactly? what is it by default?

2020-12-04 12:19 UTC, peter-pycom commented on content/firmwareapi/pycom/network/wlan.md
> +    With our development boards it defaults to using the internal antenna, but in the case of an OEM module, the antenna pin (`P12`) is not used, so it's free to be used for other things.	With our de
duplicated

2020-12-04 12:50 UTC, gijsio commented on content/firmwareapi/pycom/network/bluetooth/_index.md
I think the small examples in between, like this, make the API pages cluttered.

2021-04-09 11:38 UTC, peter-pycom approved these changes

2021-04-09 11:38 UTC, merged