included tutorial on nvram usage
pycom/pycom-documentation pull request #350
Opened 2020-12-04 09:46 UTC by gijsio

2020-12-04 12:12 UTC, peter-pycom requested changes

2020-12-04 12:12 UTC, peter-pycom commented on content/tutorials/networks/lora/nvram.md
> +app_swkey = ubinascii.unhexlify('')
do we need this initialization with unhexlify('') ? it looks strange

2020-12-04 12:12 UTC, peter-pycom commented on content/tutorials/networks/lora/nvram.md
> +    time.sleep(0.1) #be able to ctrl+c out of this
why would anyone want to ctrl-c out of this 1 sec sleep in the middle of the example? I would keep it simple and just 

time.sleep(1)

even if someone want's to ctrl c this example, they can do right before or right after this second.

what would be nice is to comment on why we need the second in the first place

2020-12-04 12:45 UTC, gijsio commented on content/tutorials/networks/lora/nvram.md
> +    time.sleep(0.1) #be able to ctrl+c out of this
Ill change it 👍

2020-12-04 12:46 UTC, gijsio commented on content/tutorials/networks/lora/nvram.md
> +app_swkey = ubinascii.unhexlify('')
We always do it like this for the LoRa join parameters. This way you can copy the TTN values into the code

2020-12-04 12:51 UTC, peter-pycom commented on content/tutorials/networks/lora/nvram.md
> +app_swkey = ubinascii.unhexlify('')
ah, now I get it. I am supposed to fill this in to make it work (I have never tried abp before)

why not keep it consistent with the other abp example? 

https://docs.pycom.io/tutorials/networks/lora/lorawan-abp/

2020-12-04 13:12 UTC, gijsio commented on content/tutorials/networks/lora/nvram.md
> +app_swkey = ubinascii.unhexlify('')
Yes, we can :)

2021-01-15 10:39 UTC, peter-pycom approved these changes

2021-01-15 10:39 UTC, merged