Update _index.md
pycom/pycom-documentation pull request #394
Opened 2021-03-12 11:33 UTC by gijsio

removed WiFi option

2021-03-15 16:36 UTC, peter-pycom requested changes

2021-03-15 16:36 UTC, peter-pycom commented on content/gettingstarted/_index.md
> +>Note: If you do not have an expansion board, you are able to use a [USB-Serial converter](/gettingstarted/programming/usbserial/) to connect.
why not wifi/ftp?

2021-03-16 13:56 UTC, gijsio commented on content/gettingstarted/_index.md
> +>Note: If you do not have an expansion board, you are able to use a [USB-Serial converter](/gettingstarted/programming/usbserial/) to connect.
We changed the factory settings to start smart config instead of the AP, if you dont have an expansionboard, you cannot change the settings?

2021-03-16 15:29 UTC, peter-pycom commented on content/gettingstarted/_index.md
> +>Note: If you do not have an expansion board, you are able to use a [USB-Serial converter](/gettingstarted/programming/usbserial/) to connect.
ah, I see. well, then we should link the smart config option here

2021-03-19 09:01 UTC, gijsio commented on content/gettingstarted/_index.md
> +>Note: If you do not have an expansion board, you are able to use a [USB-Serial converter](/gettingstarted/programming/usbserial/) to connect.
I first thought that would be too advanced, but seeing as most beginner people get an expansionboard anyways, lets change it

2021-03-22 16:36 UTC, peter-pycom approved these changes

2021-03-22 16:37 UTC, merged