Added API for uzlib
pycom/pycom-documentation pull request #402
Opened 2021-03-26 11:24 UTC by gijsio

2021-03-26 17:57 UTC, peter-pycom commented on content/firmwareapi/micropython/uzlib.md
> +data = uzlib.decompress(file, 31) #31 is the default gzip header size
weird, I get 
```
Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
TypeError: object with buffer protocol required
```
when I do 
```
import uzlib
file = open('test.txt.gz', 'r')
content = file.read()
s = uzlib.decompress(content, 31)
# print(len(s))
```

I get 
```
Traceback (most recent call last):
  File "<stdin>", line 5, in <module>
ValueError: -3
```

2021-03-26 21:02 UTC, gijsio commented on content/firmwareapi/micropython/uzlib.md
> +data = uzlib.decompress(file, 31) #31 is the default gzip header size
I copied the wrong thing :/
Should be this:
```
file = open('test.txt.gz', 'r') #do not .read(), this will change the stream
data = uzlib.DecompIO(file, 31)
print(data.readline())
```
With a file test.txt compressed using gzip, containing 'hello world', we get output:
```
b'hello world\n'
```

2021-03-29 08:49 UTC, peter-pycom commented
How about a python-only example. Maybe there are some OS specific things in gzip ... 

compress.py:
```
# run this with python3 on the computer
# then upload test.txt.z to the pycom device (adjust 'Project settings' in Pymakr)
import zlib
import os

s = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.\n'
b = bytes(u, "utf-8")
z = zlib.compress(s)
with open('test.txt.z', 'wb') as f:
    f.write(z)
print('ratio', len(z)/len(s))
```

decompress.py:
```
import zlib
import os

# verify that the file has been uploaded
file = 'test.txt.z'
print('dir', os.listdir())
print(file, os.stat(file))

# read contents, decompress and print
with open(file, 'rb') as f:
    z = f.read()
b = zlib.decompress(z)
s = b.decode('utf-8')
print('ratio', len(z)/len(s))
print(s)
```

2021-04-09 11:23 UTC, peter-pycom requested changes

2021-04-09 11:23 UTC, peter-pycom commented on content/tutorials/advanced/uzlib.md
> +add text
echo "Hallo" > test.txt

2021-04-09 11:23 UTC, peter-pycom commented on content/tutorials/advanced/uzlib.md
> +file = open(file, 'r') #do not .read(), this will change the stream
with

2021-04-09 11:23 UTC, peter-pycom commented on content/tutorials/advanced/uzlib.md
> +print(data.readline())
read whole file

2021-04-09 11:23 UTC, peter-pycom commented on content/tutorials/advanced/uzlib.md
> +The Pycom firmware includes the [`uzlib`](/firmwareapi/micropython/uzlib/) module by default, which supports the decompression of files and streams. Below, three usage examples are highlighted:
two

2021-04-12 12:00 UTC, gijsio commented on content/tutorials/advanced/uzlib.md
> +file = open(file, 'r') #do not .read(), this will change the stream
with does not work with DecompIO (missing __exit__), added it for open(file,..)

2021-04-13 09:02 UTC, peter-pycom requested changes

2021-04-13 09:02 UTC, peter-pycom commented on content/tutorials/advanced/uzlib.md
>  touch test.txt
no need for touch. echo will create it

2021-07-01 13:06 UTC, peter-pycom approved these changes

2021-07-01 13:07 UTC, merged