added LTE information
pycom/pycom-documentation pull request #429
Opened 2021-06-04 09:55 UTC by gijsio

Added index, general remarks and Pycom simcard information

2021-06-04 17:08 UTC, peter-pycom requested changes

2021-06-04 17:08 UTC, peter-pycom commented on content/tutorials/networks/lte/_index.md
> -    print(lte.send_at_cmd('ATI1'))
Why do you remove the ATI1 method? If anything, we might want to promote it, no?!

2021-06-04 17:08 UTC, peter-pycom commented on content/tutorials/networks/lte/_index.md
> +Below you can find a detailled troubleshooting guide discussing
detailled  -> detailed

2021-06-04 17:08 UTC, peter-pycom commented on content/tutorials/networks/lte/_index.md
> +When using the Pycom simcard, you can use the above example to connect to the Vodafone LTE network using `apn=pycom.io`. Leaving the band open will allow the modem to scan all bands. You can use the
At the very least with NB-IoT you really shouldn't leave the band empty. It can take very/too long

2021-06-04 17:08 UTC, peter-pycom commented on content/tutorials/networks/lte/_index.md
> +When using the Pycom simcard, you can use the above example to connect to the Vodafone LTE network using `apn=pycom.io`. Leaving the band open will allow the modem to scan all bands. You can use the
Please put at least a paragraph before going into DNS troubleshooting

2021-06-04 17:08 UTC, peter-pycom commented on content/tutorials/networks/lte/_index.md
> +When using the Pycom simcard, you can use the above example to connect to the Vodafone LTE network using `apn=pycom.io`. Leaving the band open will allow the modem to scan all bands. You can use the
Please put at least a paragraph before going into DNS troubleshooting

2021-06-04 17:08 UTC, peter-pycom commented on content/tutorials/networks/lte/_index.md
> +When using the Pycom simcard, you can use the above example to connect to the Vodafone LTE network using `apn=pycom.io`. Leaving the band open will allow the modem to scan all bands. You can use the
pybytes -> Pybytes

2021-06-14 14:02 UTC, gijsio commented on content/tutorials/networks/lte/_index.md
> -    print(lte.send_at_cmd('ATI1'))
I want to be consistent in the option we give. There is also `lte.send_at_cmd('showver')` and probably more options that we don't explicitely show. If we have one (`sqnsupgrade.info()`) that 'always' works, even if the modem is in ppp-mode or whatever, it is also less confusing.

2021-06-15 11:06 UTC, peter-pycom commented on content/tutorials/networks/lte/_index.md
> -    print(lte.send_at_cmd('ATI1'))
Consistency is valuable, however we still have the problem that sqnsupgrade.info() can core dump, so I want to be pragmatic and directly offer an alternative. And while yes, many roads lead to Rome, ATI1 is my proposal here.

I don't think sqnsupgrade.info() will work if the modem is in ppp mode. (And even if it would somehow happen to work, I don't intend to support that. For all I understand it would be some weird corner case/bug that makes it work, which might go away without notice)

2021-06-21 14:07 UTC, gijsio commented on content/tutorials/networks/lte/_index.md
> -    print(lte.send_at_cmd('ATI1'))
Alright, I'll add ATI1 back in :)

2021-06-21 17:30 UTC, peter-pycom approved these changes

2021-06-25 08:33 UTC, merged